In [ ]:
import numpy as np

In [ ]:
np.zeros


<function numpy.zeros>

In [ ]:
a = np.zeros([3,3])


In [ ]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a[0,:] =1

In [ ]:
a



array([[1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.all(a == 1, axis=1)

array([ True, False, False])

In [ ]:
 np.any(np.all(a == 1, axis=1))

True