In [ ]:
import numpy as np
from skimage.transform import rescale
import scipy
import scipy.ndimage
import cv2
import os

In [ ]:
FILENAME = 'teste_text.png'
PATH = os.path.join('assets', FILENAME)
img = cv2.imread(PATH)

In [ ]:
img

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [ ]:
cv2.imshow('original_image', img)

In [ ]:
# desmembrando as cores da imagem


In [ ]:
img.ndim

3

In [ ]:
# red green blue

In [ ]:
img[0]

array([[255, 255, 255],
       [255, 255, 255],
       [255, 255, 255],
       ...,
       [255, 255, 255],
       [255, 255, 255],
       [255, 255, 255]], dtype=uint8)

In [ ]:
img[0].shape

(1289, 3)

In [ ]:
img.shape

(525, 1289, 3)

In [ ]:
(1 / 9) * np.array([[1, 1, 1],
                                [1, 1, 1],
                                [1, 1, 1]])

array([[0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111]])

In [ ]:

# Box Blur
box_blur =np.array([[1, 1, 1],
                                [1, 1, 1],
                                [1, 1, 1]])

In [ ]:
box_factor = 1/box_blur.sum()*box_blur



In [ ]:
box_factor

array([[0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111]])