In [ ]:
import cv2
import numpy as np
import scipy
import scipy.ndimage
from scipy import signal

In [ ]:
kernlen=5

In [ ]:
std=5

In [ ]:
signal.gaussian(kernlen, std=std).reshape(kernlen, 1)

array([[0.92311635],
       [0.98019867],
       [1.        ],
       [0.98019867],
       [0.92311635]])

In [ ]:
signal.gaussian(kernlen, std=std)

array([0.92311635, 0.98019867, 1.        , 0.98019867, 0.92311635])

In [ ]:
generate_kernel1d = signal.gaussian(kernlen, std=std).reshape(kernlen, 1)

In [ ]:
generate_kernel2d = np.outer(generate_kernel1d, generate_kernel1d)

In [ ]:
generate_kernel2d

array([[0.85214379, 0.90483742, 0.92311635, 0.90483742, 0.85214379],
       [0.90483742, 0.96078944, 0.98019867, 0.96078944, 0.90483742],
       [0.92311635, 0.98019867, 1.        , 0.98019867, 0.92311635],
       [0.90483742, 0.96078944, 0.98019867, 0.96078944, 0.90483742],
       [0.85214379, 0.90483742, 0.92311635, 0.90483742, 0.85214379]])

In [ ]:
def generate_kernel(kernlen=5, std=5):
    '''
    Retorna 2D Gaussian kernel array

    - A função signal.gaussian da biblioteca scipy é usada para gerar um kernel gaussiano 1D.
    - Para converter o kernel Gaussiano 1D em um kernel Gaussiano 2D, a função np.outer é usada.
    - Nesse caso, é necessário generate_kernel1d (o kernel gaussiano 1D) como ambos os vetores de entrada, multiplicando efetivamente o kernel 1D por si mesmo, 
    resultando em um kernel gaussiano 2D.
    - Finalmente, a função retorna o kernel Gaussiano 2D gerado como uma matriz numpy 2D.
    '''
    generate_kernel1d = signal.gaussian(kernlen, std=std).reshape(kernlen, 1)
    generate_kernel2d = np.outer(generate_kernel1d, generate_kernel1d) # multiplica ele por ele mesmo
    return generate_kernel2d

In [ ]:
kernel = generate_kernel(23, std=20)

In [ ]:
kernel

array([[0.73896849, 0.75862325, 0.77685621, 0.79354106, 0.80856032,
        0.82180676, 0.83318464, 0.84261089, 0.85001609, 0.85534533,
        0.85855889, 0.85963276, 0.85855889, 0.85534533, 0.85001609,
        0.84261089, 0.83318464, 0.82180676, 0.80856032, 0.79354106,
        0.77685621, 0.75862325, 0.73896849],
       [0.75862325, 0.77880078, 0.7975187 , 0.81464732, 0.83006605,
        0.84366482, 0.85534533, 0.86502229, 0.87262445, 0.87809543,
        0.88139447, 0.8824969 , 0.88139447, 0.87809543, 0.87262445,
        0.86502229, 0.85534533, 0.84366482, 0.83006605, 0.81464732,
        0.7975187 , 0.77880078, 0.75862325],
       [0.77685621, 0.7975187 , 0.81668648, 0.83422678, 0.85001609,
        0.86394169, 0.87590293, 0.88581248, 0.89359735, 0.89919982,
        0.90257815, 0.90370708, 0.90257815, 0.89919982, 0.89359735,
        0.88581248, 0.87590293, 0.86394169, 0.85001609, 0.83422678,
        0.81668648, 0.7975187 , 0.77685621],
       [0.79354106, 0.81464732, 0.83422678, 0.852

In [ ]:
kernel_tile = np.tile(kernel, (4))

In [ ]:
kernel_tile

array([[0.73896849, 0.75862325, 0.77685621, ..., 0.77685621, 0.75862325,
        0.73896849],
       [0.75862325, 0.77880078, 0.7975187 , ..., 0.7975187 , 0.77880078,
        0.75862325],
       [0.77685621, 0.7975187 , 0.81668648, ..., 0.81668648, 0.7975187 ,
        0.77685621],
       ...,
       [0.77685621, 0.7975187 , 0.81668648, ..., 0.81668648, 0.7975187 ,
        0.77685621],
       [0.75862325, 0.77880078, 0.7975187 , ..., 0.7975187 , 0.77880078,
        0.75862325],
       [0.73896849, 0.75862325, 0.77685621, ..., 0.77685621, 0.75862325,
        0.73896849]])

In [ ]:
kernel = generate_kernel()

In [ ]:
kernel

array([[0.85214379, 0.90483742, 0.92311635, 0.90483742, 0.85214379],
       [0.90483742, 0.96078944, 0.98019867, 0.96078944, 0.90483742],
       [0.92311635, 0.98019867, 1.        , 0.98019867, 0.92311635],
       [0.90483742, 0.96078944, 0.98019867, 0.96078944, 0.90483742],
       [0.85214379, 0.90483742, 0.92311635, 0.90483742, 0.85214379]])

In [ ]:
kernel_tile = np.tile(kernel, (4))
kernel_tile

array([[0.85214379, 0.90483742, 0.92311635, 0.90483742, 0.85214379,
        0.85214379, 0.90483742, 0.92311635, 0.90483742, 0.85214379,
        0.85214379, 0.90483742, 0.92311635, 0.90483742, 0.85214379,
        0.85214379, 0.90483742, 0.92311635, 0.90483742, 0.85214379],
       [0.90483742, 0.96078944, 0.98019867, 0.96078944, 0.90483742,
        0.90483742, 0.96078944, 0.98019867, 0.96078944, 0.90483742,
        0.90483742, 0.96078944, 0.98019867, 0.96078944, 0.90483742,
        0.90483742, 0.96078944, 0.98019867, 0.96078944, 0.90483742],
       [0.92311635, 0.98019867, 1.        , 0.98019867, 0.92311635,
        0.92311635, 0.98019867, 1.        , 0.98019867, 0.92311635,
        0.92311635, 0.98019867, 1.        , 0.98019867, 0.92311635,
        0.92311635, 0.98019867, 1.        , 0.98019867, 0.92311635],
       [0.90483742, 0.96078944, 0.98019867, 0.96078944, 0.90483742,
        0.90483742, 0.96078944, 0.98019867, 0.96078944, 0.90483742,
        0.90483742, 0.96078944, 0.98019867, 0

In [ ]:
# o codigo a cima repetiu o kernel 4 vezes

In [ ]:
kernel_tile = np.tile(kernel, (3, 1, 1))

In [ ]:
kernel_tile

array([[[0.85214379, 0.90483742, 0.92311635, 0.90483742, 0.85214379],
        [0.90483742, 0.96078944, 0.98019867, 0.96078944, 0.90483742],
        [0.92311635, 0.98019867, 1.        , 0.98019867, 0.92311635],
        [0.90483742, 0.96078944, 0.98019867, 0.96078944, 0.90483742],
        [0.85214379, 0.90483742, 0.92311635, 0.90483742, 0.85214379]],

       [[0.85214379, 0.90483742, 0.92311635, 0.90483742, 0.85214379],
        [0.90483742, 0.96078944, 0.98019867, 0.96078944, 0.90483742],
        [0.92311635, 0.98019867, 1.        , 0.98019867, 0.92311635],
        [0.90483742, 0.96078944, 0.98019867, 0.96078944, 0.90483742],
        [0.85214379, 0.90483742, 0.92311635, 0.90483742, 0.85214379]],

       [[0.85214379, 0.90483742, 0.92311635, 0.90483742, 0.85214379],
        [0.90483742, 0.96078944, 0.98019867, 0.96078944, 0.90483742],
        [0.92311635, 0.98019867, 1.        , 0.98019867, 0.92311635],
        [0.90483742, 0.96078944, 0.98019867, 0.96078944, 0.90483742],
        [0.85214

In [ ]:
# agora temos 3 versões do mesmo array para cada camada de cor


In [ ]:
# %%
kernel_tile = np.tile(kernel, (1, 1, 3))

In [ ]:
kernel_tile

array([[[0.85214379, 0.90483742, 0.92311635, 0.90483742, 0.85214379,
         0.85214379, 0.90483742, 0.92311635, 0.90483742, 0.85214379,
         0.85214379, 0.90483742, 0.92311635, 0.90483742, 0.85214379],
        [0.90483742, 0.96078944, 0.98019867, 0.96078944, 0.90483742,
         0.90483742, 0.96078944, 0.98019867, 0.96078944, 0.90483742,
         0.90483742, 0.96078944, 0.98019867, 0.96078944, 0.90483742],
        [0.92311635, 0.98019867, 1.        , 0.98019867, 0.92311635,
         0.92311635, 0.98019867, 1.        , 0.98019867, 0.92311635,
         0.92311635, 0.98019867, 1.        , 0.98019867, 0.92311635],
        [0.90483742, 0.96078944, 0.98019867, 0.96078944, 0.90483742,
         0.90483742, 0.96078944, 0.98019867, 0.96078944, 0.90483742,
         0.90483742, 0.96078944, 0.98019867, 0.96078944, 0.90483742],
        [0.85214379, 0.90483742, 0.92311635, 0.90483742, 0.85214379,
         0.85214379, 0.90483742, 0.92311635, 0.90483742, 0.85214379,
         0.85214379, 0.9048374