### Linear Algebra

In [2]:
import numpy as np

In [3]:
a = np.ones([2,3])
print(a)

print()

b = np.full([3,2], 5)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]

[[5 5]
 [5 5]
 [5 5]]


In [4]:
# Retorno de erro se tentamos multiplicar matrizes de tamanhos diferentes
a * b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [5]:
# note inclusive que A x B != B x A
np.matmul(a,b) # multiplicação matricial
# np.matmul(b,a)

array([[15., 15.],
       [15., 15.]])

In [6]:
# Encontrar o determinante
identidade = np.identity(3)
identidade

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Determinante :

In [7]:
# Pra quem esta familiarizado com Algebra Linear, sabe que o determinante de uma matriz identidade é = 1
np.linalg.det(identidade)

1.0

In [ ]:
# Existem diversas outras composições matemáticas que não serão importantes pra nós nesse curso, mas é válido dar uma estudada pra quem quiser
# Referência (https://docs.scipy.org/doc/scipy/reference/linalg.html)

### Estatística básica

In [14]:
dados = np.array([[1,2,3], [4,5,6]])
dados

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.min(dados)

1

In [17]:
np.max(dados)

6

In [18]:
# Axis 0 é coluna, axis 1 é linha
print(np.min(dados, axis=0))
print(np.min(dados, axis=1))

[1 2 3]
[1 4]


In [27]:
# Soma
print(np.sum(dados))
print(np.sum(dados, axis=0))
print(np.sum(dados, axis=1))

21
[5 7 9]
[ 6 15]


In [31]:
for i in np.transpose(dados):
    print(f"Somando {i}")
    print(np.sum(i))

Somando [1 4]
5
Somando [2 5]
7
Somando [3 6]
9


In [32]:
for i in dados:
    print(f"Somando {i}")
    print(np.sum(i))

Somando [1 2 3]
6
Somando [4 5 6]
15


In [36]:
# Média
np.mean(dados)


3.5

In [37]:
np.mean(dados, axis=0)


array([2.5, 3.5, 4.5])

In [38]:
np.mean(np.mean(dados, axis=0))

3.5

In [15]:
dados2 = np.random.randint(-5,5,size=(10,10))
dados2

array([[ 0,  0, -3,  0, -1, -4,  4,  1, -2, -1],
       [ 2, -4,  2, -1,  2, -4,  3,  1, -3,  3],
       [ 4,  2,  1,  3, -1, -1, -3,  1,  1,  1],
       [ 0,  1, -3,  1, -3,  4, -5, -5,  0, -4],
       [-5, -2, -4,  0,  0, -5,  2, -5, -4,  0],
       [-5,  2,  4,  0,  1,  4, -1,  4, -4, -3],
       [-2,  2,  2,  1, -4,  1, -1, -5, -4,  2],
       [-2,  0, -3, -2, -1, -4, -2, -2, -1,  0],
       [-2,  0,  3, -4, -1, -1, -4,  3,  0,  1],
       [ 0,  3,  3, -3, -2, -3, -3,  0, -2, -3]])

In [22]:
np.min(dados2)

-5

In [24]:
# Axis 0 é coluna, axis 1 é linha
print("Colunas: ")
print(np.min(dados2, axis=0))
print("Linhas: ")
print(np.min(dados2, axis=1))

Colunas: 
[-5 -4 -4 -4 -4 -5 -5 -5 -4 -4]
Linhas: 
[-4 -4 -3 -5 -5 -5 -5 -4 -4 -3]
