# Manipulações em linhas e colunas

In [1]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7], [8,9,1,2,3,4,5]])
print(a, a.shape)

[[1 2 3 4 5 6 7]
 [8 9 1 2 3 4 5]] (2, 7)


In [2]:
# Para pegar um item específico, utilizamos a notação [linha, coluna]
a[0, 3]
# Lembrando que na programação tendemos a contar começando do zero, então nesse exemplo temos
# linha 0 e 1
# colunas de 0 a 6

4

In [3]:
# Se quisessemos pegar só a segunda linha por ex
a[1]

array([8, 9, 1, 2, 3, 4, 5])

In [4]:
# é possivel utilizar a notação negativa de listas -na notação negativa não começamos a contar em 0
a[1, -2]

4

In [14]:
# Pegar uma coluna específica
a[:, 2]

array([3, 1])

In [5]:
# Pegar uma coluna específica
a[1, :]

array([8, 9, 1, 2, 3, 4, 5])

In [6]:
# Métodos de slicing, de listas, também funcionam aqui
# [start_index:end_index:step] -> step não é obrigatório // caso não queiramos adicionar o end_index, é só botar ':'
a[0, 1:] # coluna 1 até o final
# pode parecer meio confuso entre as virgulas e os dois pontos mas a ideia é:
# a[linha inicial, coluna inicial: linha final, index final, passo (step)]

array([2, 3, 4, 5, 6, 7])

In [7]:
print(a)

[[1 2 3 4 5 6 7]
 [8 9 1 2 3 4 5]]


In [9]:
a[0, 1: 5] # coluna 1 até a 5

array([2, 3, 4, 5])

In [11]:
a[1, 0::2] # step de 2 em 2

array([8, 1, 3, 5])

In [12]:
# se o step for negativo, podemos inverter a matriz
a[::-1]

array([[8, 9, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 6, 7]])

In [13]:
# se o step for negativo, podemos inverter a matriz
a[:,::-1]

array([[7, 6, 5, 4, 3, 2, 1],
       [5, 4, 3, 2, 1, 9, 8]])

### Atribuição de valores

In [15]:
a = np.array([[1,2,3,4,5,6,7], [8,9,1,2,3,4,5]])

In [16]:
a[1,5] = 34     # mudando o item na linha 1 (que representa a segunda), coluna 5
print(a)
print()
a[:,2] = 35     # todas as linhas, da coluna 2
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9  1  2  3 34  5]]

[[ 1  2 35  4  5  6  7]
 [ 8  9 35  2  3 34  5]]


### Exemplo 3D - Tridimensional

In [17]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
# Pegar um elemento específico (trabalhamos de fora pra dentro)
# Queremos a primeira matriz [0]
b[0]

array([[1, 2],
       [3, 4]])

In [19]:
# Na sequencia queremos acessar a segunda linha [1]
b[0, 1]

array([3, 4])

In [20]:
# E então queremos pegar o primeiro elemento [0]
b[0, 1, 0]

3

In [21]:
# Digamos que eu quisesse pegar toda a primeira linha da segunda dimensão
b[1, 0, :]

array([5, 6])

In [22]:
# Ou toda a segunda coluna da primeira dimensão
b[0, :, 1]

array([2, 4])

In [23]:
# Brinquem com esses valores para se acostumarem com o slicing

In [24]:
# é possível fazer reposição de valores de mesma dimensão no Numpy usando essa lógica, como por ex.:
b[0, 1] = [22, 23]      # alterando a segunda linha da primeira dimensão
print(b)
# Se não fosse da mesma dimensão, teríamos um erro, pra verificar essa dimensão é possível usar .shape em slicing

[[[ 1  2]
  [22 23]]

 [[ 5  6]
  [ 7  8]]]


In [25]:
b[0, 1].shape # 1d values retornam só um valor iteravel

(2,)

In [26]:
b[0].shape

(2, 2)

In [27]:
c= np.array([0])
c.shape

(1,)