# Inicializando tipos diferentes de Arrays
### Zeros/Ones

In [1]:
import numpy as np
np.zeros(3)

array([0., 0., 0.])

In [2]:
np.zeros([3, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
np.zeros([2, 3, 5])

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [4]:
np.ones([4,2,2])
# np.ones([4,2,2], dytype='int32')

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

### Outros números/aleatórios

In [5]:
# Qualquer outro numero
np.full([3, 3], 21)

array([[21, 21, 21],
       [21, 21, 21],
       [21, 21, 21]])

In [6]:
# full_like method -> reutilização de arrays para preenchimento
# primeiro declaramos a matriz que iremos transfromar
a = np.array([[1,2,3,4,5,6,7], [8,9,1,2,3,4,5]])
print(a)

[[1 2 3 4 5 6 7]
 [8 9 1 2 3 4 5]]


In [7]:
np.full_like(a, 25)

array([[25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25]])

In [8]:
# Números aleatórios
# decimais -> estamos trabalhando com .rand(), nessa função não precisamos passar uma lista dentro para informar o shape
np.random.rand(2, 2, 3)

array([[[0.8424279 , 0.81354395, 0.53268285],
        [0.29293985, 0.8154272 , 0.49912383]],

       [[0.15092828, 0.00428354, 0.51569147],
        [0.46342796, 0.90695573, 0.86631925]]])

In [9]:
# Random integers
# randint(limites, size=(shape))
np.random.randint(7, size=(2,3,5))

array([[[5, 6, 4, 6, 4],
        [5, 5, 4, 5, 1],
        [1, 5, 6, 4, 6]],

       [[4, 1, 6, 1, 6],
        [3, 6, 3, 2, 3],
        [0, 6, 3, 4, 6]]])

In [10]:
np.random.randint(5, 8, size=(2,3,5))

array([[[5, 7, 6, 7, 7],
        [6, 5, 5, 7, 5],
        [7, 5, 5, 5, 7]],

       [[6, 7, 6, 7, 6],
        [6, 5, 6, 6, 5],
        [7, 7, 7, 6, 7]]])

### Operações de algebra (chatinho, eu sei)

In [11]:
# matriz identidade só precisa de 1 parametro, pq naturalmente ela é uma matriz quadrada
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# Repetição de arrays em linhas
ex = np.array([1, 2, 3])
np.repeat(ex, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [13]:
# Repetição de arrays em colunas
# A repetição em colunas funciona pq transformamos o array em duas dimensões (adicionando mais colchetes)
ex = np.array([[1, 2, 3]])
np.repeat(ex, 3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])